pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
        dir('/home/ubuntu/flask-express-app/frontend') {
          git branch: 'main', url: 'https://github.com/kumar-animesh28/flask-express-app.git'
        }
      }
    }

    stage('Install Dependencies') {
      steps {
        dir('/home/ubuntu/flask-express-app/frontend') {
          sh 'npm install'
        }
      }
    }

    stage('Restart Service') {
      steps {
        sh 'sudo systemctl restart express-app'
      }
    }
  }
}
