pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
        git branch: 'main', url: 'git@github.com:kumar-animesh28/flask-express-app.git'
      }
    }

    stage('Install Dependencies') {
      steps {
        dir('frontend') {
          sh 'npm install'
        }
      }
    }

    stage('Restart Service') {
      steps {
        sh 'sudo systemctl restart express-app'
      }
    }
  }
}
