pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
        // Checkout in Jenkins workspace
        dir('frontend') {
          git branch: 'main', url: 'https://github.com/kumar-animesh28/flask-express-app.git'
        }
      }
    }

    stage('Install Dependencies') {
      steps {
        dir('frontend') {
          sh 'npm install'
        }
      }
    }

    stage('Deploy') {
      steps {
        sh '''
          # Sync frontend code to live directory
          rsync -a --delete frontend/ /home/ubuntu/flask-express-app/frontend/
          sudo systemctl restart express-app
        '''
      }
    }
  }
}
