pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
        // Checkout in Jenkins workspace
        dir('backend') {
          git branch: 'main', url: 'https://github.com/kumar-animesh28/flask-express-app.git'
        }
      }
    }

    stage('Install Dependencies') {
      steps {
        dir('backend') {
          sh '''
            #!/bin/bash
            if [ ! -d ".venv" ]; then
              python3 -m venv .venv
            fi
            # Activate virtualenv for this shell
            . .venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
          '''
        }
      }
    }

    stage('Deploy') {
      steps {
        sh '''
          # Sync backend code to live directory
          rsync -a --delete backend/ /home/ubuntu/flask-express-app/backend/
          sudo systemctl restart flask-app
        '''
      }
    }
  }
}
