pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
        dir('/home/ubuntu/flask-express-app/backend') {
          git branch: 'main', url: 'https://github.com/kumar-animesh28/flask-express-app.git'
        }
      }
    }

    stage('Install Dependencies') {
      steps {
        dir('/home/ubuntu/flask-express-app/backend') {
          sh '''#!/bin/bash
. .venv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt
'''
        }
      }
    }

    stage('Restart Service') {
      steps {
        sh 'sudo systemctl restart flask-app'
      }
    }
  }
}
