pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/kumar-animesh28/flask-express-app.git'
      }
    }

    stage('Install Dependencies') {
      steps {
        dir('backend') {
          sh '''#!/bin/bash
python3 -m venv .venv
. .venv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt
'''
        }
      }
    }

    stage('Restart Service') {
      steps {
        sh 'sudo systemctl restart flask-app'
      }
    }
  }
}
